### ISSUE TITLE
Should we rewrite the entire engine from the start?

### ISSUE THREAD

**Issue by holywyvern** [holywyvern/mv-pixi-upgrade#6]
After all the performance is poorly, and it may be better to just rewrite the entire formart to work with things like PIXI's loader.

Still, I want somehow to mantain compatibility for plugins, even if I mark some functions as deprecated in an extra file made as a "compatibility layer"

**Comment by ivanpopelyshev** [comment]
Dont do that please :) Lets try fix this one first.

**Comment by holywyvern** [comment]
Let's try to just upgrade then.
Marked as closed
